
run-shell ~/clone/path/sensible.tmux

set-option -g default-shell /bin/zsh

set -g default-terminal "screen-256color"

set-option -g default-command "reattach-to-user-namespace -l zsh"

#clock
set-window-option -g clock-mode-colour colour100

#pane number display 
set-option -g display-panes-active-colour colour34
set-option -g display-panes-colour colour166

set-option -g mouse-select-pane on
set-option -g mouse-select-window on

set-option -g display-panes-time 2000

#Count from 1!!
set -g base-index 1
setw -g pane-base-index 1

set-window-option -g mode-keys vi

bind -T copy-mode-vi 'v' send-keys -X begin-selection 
bind -T copy-mode-vi 'y' send-keys -X copy-selection

### KEYS ###
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

#using C-a as prefix
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

unbind /
bind / last-window

unbind %
bind s split-window -v
unbind '"'
bind v split-window -h

unbind left
unbind down
unbind up
unbind right

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


bind H swap-pane -U
bind L swap-pane -D

bind Left  resize-pane -L
bind Right resize-pane -R

bind -n S-Right resize-pane -R 15
bind -n S-Left  resize-pane -L 16 

bind Escape copy-mode
bind p paste-buffer

unbind o
bind o select-pane -t :.-


bind C-c run "tmux save-buffer - | pbcopy"
bind C-v run "tmux set-buffer \"$(pbpaste)\"; tmux paste-buffer"

bind C-s choose-session

