export EDITOR="/opt/homebrew/bin/nvim"

# move this to .zprofile?
export HOME="/Users/paulw"

HISTFILE="$HOME/.histfile"
HISTSIZE=1000000
SAVEHIST=1000000

# Prevent insert key from changing input mode.
# (switch to Emacs mode)
bindkey -e

setopt HIST_VERIFY
#setopt SHARE_HISTORY

# Ignore duplicate in history.
setopt hist_ignore_dups

setopt EXTENDED_HISTORY 

setopt HIST_IGNORE_DUPS
setopt HIST_REDUCE_BLANKS

setopt NO_HIST_BEEP

setopt NO_BEEP


if [[ -r "$HOME/.aliasrc" ]]; then 
	source "$HOME/.aliasrc"
fi

path+=("$HOME/.cargo/bin" "$HOME/.local/bin")
export PATH

# Not all servers have terminfo for rxvt-256color. :<
if [ "${TERM}" = 'rxvt-256color' ] && ! [ -f '/usr/share/terminfo/r/rxvt-256color' ] && ! [ -f '/lib/terminfo/r/rxvt-256color' ] && ! [ -f "${HOME}/.terminfo/r/rxvt-256color" ]; then
    export TERM='rxvt-unicode'
fi

# alias -g latest='*(om[1])'

export TMP="$HOME/tmp"
export TEMP="$TMP"
export TMPDIR="$TMP"


# Fancy cd that can cd into parent directory, if trying to cd into file.
# useful with ^F fuzzy searcher.
cd() {
    if (( $+2 )); then
        builtin cd "$@"
        return 0
    fi

    if [ -f "$1" ]; then
        echo "${yellow}cd ${1:h}${NC}" >&2
        builtin cd "${1:h}"
    else
        builtin cd "${@}"
    fi
}

# Control-x-e to open current line in $EDITOR, awesome when writting functions or editing multiline commands.
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

# Ignore lines prefixed with '#'.
setopt interactivecomments


# Nobody need flow control anymore. Troublesome feature.
# 3.15: Why can't I bind \C-s and \C-q any more?
# The control-s and control-q keys now do flow control by default, unless you have turned this off with stty -ixon or redefined the keys which control it with stty start or stty stop. (This is done by the system, not zsh; the shell simply respects these settings.) In other words, \C-s stops all output to the terminal, while \C-q resumes it.  To stop zsh from allowing flow control and hence restoring the use of the keys: put setopt noflowcontrol in your .zshrc file.
#stty -ixon
setopt noflowcontrol

if [ -f ~/.alert ]; then echo '>>> Check ~/.alert'; fi

SETUP_DIR="$HOME/repos/setup/dotfiles/zsh"

autoload -Uz colors 
colors

fpath=("$FPATH_DIR/zsh-completions/src" "${fpath[@]}")
autoload -Uz compinit
compinit

FPATH_DIR="$SETUP_DIR/func"
fpath=("$FPATH_DIR/zsh-completions/src" "${fpath[@]}")
autoload shutdown

# Completion.
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' menu select=2
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion:*:descriptions' format '%U%F{cyan}%d%f%u'

PLUGIN_DIR="$SETUP_DIR/plugins"

source $PLUGIN_DIR/liquidprompt/liquidprompt.plugin.zsh

source $PLUGIN_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh
source $PLUGIN_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $PLUGIN_DIR/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey "^[[B" history-substring-search-down
bindkey "^[[A" history-substring-search-up

source $PLUGIN_DIR/zsh-you-should-use/you-should-use.plugin.zsh
source $PLUGIN_DIR/z/z.sh
source $PLUGIN_DIR/oh-my-zsh/plugins/command-not-found/command-not-found.plugin.zsh
source $PLUGIN_DIR/oh-my-zsh/plugins/common-aliases/common-aliases.plugin.zsh
source $PLUGIN_DIR/oh-my-zsh/plugins/git/git.plugin.zsh
source $PLUGIN_DIR/oh-my-zsh/plugins/git-extras/git-extras.plugin.zsh

source "$HOME/.aliasrc"
source "$HOME/.workrc"


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
alias deploy_tool=/Users/paulw/polez/tools/deploy/deploy_tool/main.py
